export default {
  departments: [
    { key: 1, label: "急救/重症" },
    { key: 2, label: "门诊" },
    { key: 3, label: "后勤" },
    { key: 4, label: "指挥" },
    { key: 5, label: "重症" },
    { key: 6, label: "超声" },
    { key: 7, label: "清创" },
    { key: 8, label: "留观" },
    { key: 9, label: "药房" },
    { key: 10, label: "耗材" },
    { key: 11, label: "手术" },
    { key: 12, label: "防疫/隔离" },
    { key: 13, label: "消毒" },
    { key: 14, label: "住院" },
    { key: 15, label: "检验" },
  ],
  title: "深圳多特医疗技术有限公司",
};
