module.exports = {
  purge: {
    content: ["./index.html", "./website/**/*.{vue,js,ts,jsx,tsx}"],
    safelist: [
      "bg-box",
      "bg-box-hover",
      "bg-modal-ultralight",
      "bg-modal-lighter",
      "bg-modal-light",
      "bg-modal-heavy",
      "bg-modal-bold",
      "w-modal-ultralight",
      "w-modal-lighter",
      "w-modal-light",
      "w-modal-heavy",
      "w-modal-bold",
      "h-modal-ultralight",
      "h-modal-lighter",
      "h-modal-light",
      "h-modal-heavy",
      "h-modal-bold",
    ],
  },
  darkMode: "class",
  important: true,
  theme: {
    extend: {
      backgroundImage: (theme) => ({
        box: "url('assets/bg_box.png')",
        "box-hover": "url('assets/bg_box_hover.png')",
        "modal-ultralight": "url('assets/bg_modal_dark_ultralight.png')",
        "modal-lighter": "url('assets/bg_modal_dark_lighter.png')",
        "modal-light": "url('assets/bg_modal_dark_light.png')",
        "modal-heavy": "url('assets/bg_modal_dark_heavy.png')",
        "modal-bold": "url('assets/bg_modal_dark_bold.png')",
      }),
      colors: {
        primary: "#1890FF",
        danger: "#FF6061",
        warning: "#F08E3A",
        success: "#00C44A",
        "navy-1": "#0E518F",
        "navy-2": "#0B4070",
        "navy-3": "#06315D",
        "navy-4": "#042546",
        "navy-5": "#051D33",
        "box-pink": "#F895BB",
        "box-red": "#E03C3D",
        "box-brown": "#810000",
        "box-cream": "#EDE3D6",
        "box-yellow": "#D8BE00",
        "box-green": "#00C44A",
        "box-blue-1": "#19BAF4",
        "box-blue-2": "#1890FF",
        "box-blue-3": "#0E518F",
      },
      fontSize: {
        12: ["12px", "20px"],
        14: ["14px", "22px"],
        16: ["16px", "24px"],
        18: ["18px", "26px"],
        20: ["20px", "24px"],
        22: ["22px", "30px"],
        24: ["24px", "28px"],
      },
      height: {
        "modal-ultralight": "264px",
        "modal-lightermin": "314px",
        "modal-lighter": "320px",
        "modal-lightmin": "411px",
        "modal-light": "432px",
        "modal-heavy": "560px",
        "modal-bold": "748px",
      },
      width: {
        "modal-ultralight": "620px",
        "modal-lightermin": "314px",
        "modal-lighter": "620px",
        "modal-light": "620px",
        "modal-heavy": "920px",
        "modal-bold": "1416px",
      },
      spacing: {
        4: "4px",
        8: "8px",
        10: "10px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        28: "28px",
        32: "32px",
        36: "36px",
        40: "40px",
        44: "44px",
        48: "48px",
        52: "52px",
        56: "56px",
        60: "60px",
        64: "64px",
        68: "68px",
        72: "72px",
        76: "76px",
        80: "80px",
        84: "84px",
        88: "88px",
        92: "92px",
        96: "96px",
        100: "100px",
      },
    },
  },
};
